### ISSUE TITLE
INF not reporting

### ISSUE THREAD

**Issue by jtrew89** [B-UMMI/chewBBACA#177] opened 2023-06-07 11:28 UTC
Hello,

I've been starting to use chewBBACA on an Enterobase scheme, with some in house isolates, and in general it seems to be working well. I noticed that the handful of runs that I had done so far were always reported with "No new alleles to add to schema", which seemed odd as the results_statistics.tsv had states that there have been 'INF' for each run. 

I have since checked the schema fasta files, and some have been modified on the dates of the runs and appear to have more alleles than the original schema fasta files. So, it suggests that there are inferred alleles that are not being reported in the log (attached example). Is there anyway to correct this? am I missing a parameter?

Any help would be appreciated.
Best,
JT

[07_06_23.151_250.log](https://github.com/B-UMMI/chewBBACA/files/11676420/07_06_23.151_250.log)
[results_alleles.txt](https://github.com/B-UMMI/chewBBACA/files/11676434/results_alleles.txt)
[results_statistics.txt](https://github.com/B-UMMI/chewBBACA/files/11676436/results_statistics.txt)

**Comment by ramirma** [comment] 2023-06-07 13:28
Thank you for your interest in chewBBACA @jtrew89. What you describe does not seem to be the expected behavior. To help us in clarifying what may be happening can you please upgrade to the 3.2 release (you are using 3.1.2 and this behavior may be due to a bug we fixed in the meantime) and can you provide us with the exact command you ran?
On a different note, I do not think this is the reason for the current behavior, but for reproducibility reasons it would be ideal to provide a training file for prodigal when running allele calling. You can find several training files [here](https://github.com/B-UMMI/chewBBACA/tree/master/CHEWBBACA/prodigal_training_files) or create your own.

**Comment by jtrew89** [comment] 2023-06-07 16:23
Thank you for the quick reply @ramirma , the updated release seems to have solve the issue of including INF designations within the results_alleles.txt, which is all I require really. To keep a log of the alleles being added.

I realised the problem was also caused by my somewhat Frankenstein schema. As I wanted to keep the full 3002 loci from the Enterobase schema and not lose the alleles that were being removed by PrepExternalSchema.

When I ran the un altered Enterobase schema formated by PrepExternalSchema, it rain perfectly fine, with a notification of the novel alleles identified.

Thank you for the advice on the training file, I have included that too.

**Comment by ramirma** [comment] 2023-06-07 16:30
Glad that it worked @jtrew89 ! We always advise our users to run the `PrepExternalSchema` before using an external schema in chewBBACA to avoid unwanted behavior. Watch for the upcoming release of 3.3, which will offer some additional features that may be of use to you, and do let us know if you run into another weird behavior.
Best,
Mario

**Closed by ramirma** 2023-06-07 16:30 UTC
