### ISSUE TITLE
OSError: [Errno 39] Directory not empty: '5_final_blast'

### ISSUE THREAD

**Issue by eam12** [B-UMMI/chewBBACA#112] opened 2022-01-19 02:22 UTC
I'm using version 2.8.5 of chewBBACA (installed via Conda) and am encountering the following error when I run `chewBBACA.py CreateSchema`:

> Performing final BLASTp...
>  [====================] 100%
> Removed 2 sequences that were highly similar to other sequences.
> Traceback (most recent call last):
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/bin/chewBBACA.py", line 10, in <module>
>     sys.exit(main())
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/site-packages/CHEWBBACA/chewBBACA.py", line 1480, in main
>     functions_info[process][1]()
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/site-packages/CHEWBBACA/utils/process_datetime.py", line 149, in wrapper
>     func(*args, **kwargs)
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/site-packages/CHEWBBACA/chewBBACA.py", line 193, in create_schema
>     CreateSchema.main(**vars(args))
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/site-packages/CHEWBBACA/createschema/CreateSchema.py", line 1201, in main
>     fo.delete_directory(results[1])
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/site-packages/CHEWBBACA/utils/file_operations.py", line 168, in delete_directory
>     shutil.rmtree(directory_path)
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/shutil.py", line 727, in rmtree
>     _rmtree_safe_fd(fd, path, onerror)
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/shutil.py", line 668, in _rmtree_safe_fd
>     onerror(os.rmdir, fullname, sys.exc_info())
>   File "/home/johnsont/shared/.conda/envs/chewbbaca_2.8.5/lib/python3.9/shutil.py", line 666, in _rmtree_safe_fd
>     os.rmdir(entry.name, dir_fd=topfd)
> OSError: [Errno 39] Directory not empty: '5_final_blast'

I assume this is a bug during intermediate file removal as the error **does not** occur when I include the `--no-cleanup` flag.

Thank you so much for creating such a useful tool!

**Comment by rfm-targa** [comment] 2022-01-24 11:20
Hello @eam12,

Thank you for your interest in chewBBACA. We have never encountered that error while testing/running chewBBACA. It is raised by the [`shutil`](https://docs.python.org/3/library/shutil.html) package and I do not think that it is being caused by a bug in chewBBACA. This error might be raised if you do not have sufficient permissions. Can you please check that you have sufficient permissions to delete the folder that has the intermediate files? Also, you may have problems if you are trying to modify the contents of the folder while also trying to delete it (I think this is not the case, but please check if there is a running process that might be interfering).
Please let us know if these suggestions help solve the issue.

Rafael

**Comment by saramonzon** [comment] 2022-02-18 13:43
Hi! @rfm-targa I'm having the same issue here and the permissions look good
```
drwxrwsr-x 2 smonzon bi 16K Feb 18 14:41 5_final_blast
```

**Comment by rfm-targa** [comment] 2022-02-18 16:43
Hello @saramonzon,

Thank you for reporting this issue. Please check the permissions of the files inside that folder. It is possible that some files are marked as read-only and that might lead to that error. If the issue is not related with that, the best option might be to use the `--no-cleanup` flag to avoid that error. We cannot reproduce this error, but we will include a solution to circumvent this issue in a future release.

Rafael

**Comment by saramonzon** [comment] 2022-02-24 11:53
It's weird because the directory is empty, I have used the `--no-cleanup` option and it worked fine :)

**Comment by rfm-targa** [comment] 2024-07-08 13:01
Closing this issue. We've made many changes to improve chewBBACA since the creation of this issue. Please let us know if you still need help with similar problems.

**Closed by rfm-targa** 2024-07-08 13:01 UTC
Labels: Status: In Progress
