### ISSUE TITLE
AlleleCall error due to a specific gene

### ISSUE THREAD

**Issue by MostafaYA** [B-UMMI/chewBBACA#154] opened 2023-01-05 18:14 UTC
Hi, 
Thanks for this nice software. 
I am trying to create a scheme with chewbbaca. I started with a set of genomes that are representative of the species. Some of these genomes carry a problematic gene that led to the crash of the `AlleleCall` command at the Clustering step. The error is listed below:

This is the nucleotide sequence & Translation of the gene 
ATGTTAAACTTTTTAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAAGAGCAATCAGTAAAGTATAA
Translation
MLNFLRARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARARAISKV-

```
Clusters to BLAST: 3311
 [====================] 100%Traceback (most recent call last):
  File "/home/mostafa.abdel/tools/conda/chewbbaca/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 1630, in main
    functions_info[process][1]()
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/utils/process_datetime.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 512, in allele_call
    AlleleCall.main(genome_list, loci_list, args.schema_directory,
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 2663, in main
    results = allele_calling(input_files, schema_directory, temp_directory,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 2300, in allele_calling
    match_info = process_blast_results(best_matches, config['BLAST Score Ratio']+0.1,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 1327, in process_blast_results
    bsr = cf.compute_bsr(raw_score, query_scores[query_id][1])
                                    ~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'BA0271AA-protein522_1'
```
Can I manually exclude this gene during the `CreateSchema` step? I see that schema refinement is possible, but only after the `AlleleCall` process is completed, which is not the case here

Thanks!!

**Comment by rfm-targa** [comment] 2023-01-09 13:49
Hello @MostafaYA,

Thank you for your interest in chewBBACA. That issue seems to be related with the determination of the BLASTp raw score for one representative allele (the first representative allele chosen for locus BA0271AA-protein522). chewBBACA needs to determine the BLASTp raw score of the self-alignment for all representatives, but for some sequences, such as short and repetitive sequences, BLASTp might not report any results (even when we're aligning a sequence to itself). I included some checks to deal with these cases, but it seems it was insufficient. I'll use the sequence you've shared to reproduce the error and apply a bugfix.
You can remove the problematic sequence right after schema creation. All you have to do is delete the locus' FASTA files. The schema directory should include a `BA0271AA-protein522.fasta` file and the `short` directory should include a `BA0271AA-protein522_short.fasta` file. Delete both files and you should be able to perform allele calling without further issues (provided it's the only locus with such issue).
Once again, thank you for reporting this. Feedback is essential to keep improving chewBBACA.
I'll let you know when a new version with the bugfix has been released. Don't hesitate to comment if you find any problems.

Rafael

**Comment by MostafaYA** [comment] 2023-01-09 16:19
Hi, thanks for your feedback. 
I did as you suggested but it returned `FileNotFoundError`. Somehow, it remembers the deleted files. 
```
Determining sequence length mode for all loci...Traceback (most recent call last):
  File "/home/mostafa.abdel/tools/conda/chewbbaca/bin/chewBBACA.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 1630, in main
    functions_info[process][1]()
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/utils/process_datetime.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/chewBBACA.py", line 512, in allele_call
    AlleleCall.main(genome_list, loci_list, args.schema_directory,
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 2643, in main
    loci_modes = loci_mode_file(schema_loci_fullpath, loci_modes_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/AlleleCall/AlleleCall.py", line 69, in loci_mode_file
    allele_sizes = list(fao.sequence_lengths(file).values())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/utils/fasta_operations.py", line 265, in sequence_lengths
    records = sequence_generator(fasta_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/CHEWBBACA/utils/fasta_operations.py", line 42, in sequence_generator
    records = SeqIO.parse(input_file, 'fasta')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/Bio/SeqIO/FastaIO.py", line 223, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/mostafa.abdel/tools/conda/chewbbaca/lib/python3.11/site-packages/Bio/SeqIO/Interfaces.py", line 45, in __init__
    self.stream = open(source, "r" + mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'CreateSchema/scheme/BA0257AA-protein594.fasta
``'`

**Comment by mudamaid62** [comment] 2023-01-09 17:04
Hello @MostafaYA, I also got this issue, and the solution provided by @rfm-targa works, but make sure to delete BOTH the proteinXXX.fasta file from the main schema directory and the proteinXXX_1_short.fasta from the short directory inside the main schema directory.
Best Regards.

**Comment by rfm-targa** [comment] 2023-01-09 17:28
Hello @MostafaYA,

The `.genes_list` file that's inside the schema directory includes the list of loci in the schema. It might be failing because that list still contains the name of the locus that you've deleted. That list is used when chewBBACA computes the loci sequence length modes for the first time (after that it updates the file during each run).  You should be able to circumvent this issue through one of the following methods:

- Create the schema with the `CreateSchema` module and attempt to perform allele calling with a single assembly (no need to pass more assemblies). It will fail due to the problematic locus, but it should create the file with the loci modes. After this, you can delete the FASTA files of the problematic locus and it should work as @mudamaid62 said.

- Create the schema, delete the FASTA files of the problematic locus and use the `PrepExternalSchema` to readapt the schema. The `PrepExternalSchema` is generally used to adapt schemas from other software, but it can also be used to readapt chewBBACA schemas that have been manually altered. It will automatically add the `.genes_list` to the schema (without the locus that you deleted).

Let me know if any of this methods help solve the issue. I'm working on a bugfix for this issue and you can expect a new release soon.

Rafael

**Comment by MostafaYA** [comment] 2023-01-10 09:27
@rfm-targa @mudamaid62 Thanks - it worked with method 1.

**Comment by rfm-targa** [comment] 2023-01-17 10:47
@MostafaYA , @mudamaid62,

The new release, v3.1.0, is available through [PyPI](https://pypi.org/project/chewBBACA/3.1.0/) and is awaiting approval in [Bioconda](https://github.com/bioconda/bioconda-recipes/pull/38859). This release includes a bugfix for the issue you've reported (complete list of changes available in the [Changelog](https://github.com/B-UMMI/chewBBACA/blob/master/CHANGELOG.md)).
Let me know if the new release fixes the issue (it should compute the missing scores if you create a schema from scratch and skip the computation of the BSR when the file with the scores already exists but some scores are missing).
Thank you again for reporting this issue.

Rafael

**Comment by MostafaYA** [comment] 2023-01-25 18:39
@rfm-targa I have just tested the new release (v3.1.0) on the same dataset - no errors!!!
Thanks

**Comment by rfm-targa** [comment] 2023-01-26 10:03
Thank you for the feedback, @MostafaYA. Good to know it's working as expected.
I'm closing the issue now, but feel free to reopen it if you encounter a similar problem.

**Closed by rfm-targa** 2023-01-26 10:03 UTC
Labels: Type: Bug, Priority: High, Status: In Progress
